services:
  web:
    build: .
    container_name: dream_web
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=dream_project.settings
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - dream_network

  bot:
    build: .
    container_name: dream_bot
    depends_on:
      - web
    environment:
      - DOCKER_ENV=true
      - DJANGO_API_URL=http://web:8000/api/create-dream/
      - DJANGO_API_BASE=http://web:8000/api/
      - USER_DREAMS_URL=http://web:8000/api/user-dreams/
      - LAST_DREAM_URL=http://web:8000/api/last-dream/
    command: python bot.py
    networks:
      - dream_network

networks:
  dream_network:
    driver: bridge
